### PR TITLE
i didnt like how small scratch is

### PR DESCRIPTION
**Pull request by michaeIwave**
i mainly use scratch and the stuff that clippy is saying is boring so i added some other stuff

### CODE REVIEW

**Comment by capJavert** [comment]
@KazookiTV yeah.. just a few lines.. 🤘 

I would love to merge this but you will need to do the following:
- JSON is still not valid, you can use https://jsonlint.com/ to validate your JSON syntax (this is the reason why vercel is failing)

Thanks!

**Comment by michaeIwave** [comment]
> @KazookiTV yeah.. just a few lines.. 🤘
> 
> I would love to merge this but you will need to do the following:
> 
>     * JSON is still not valid, you can use https://jsonlint.com/ to validate your JSON syntax (this is the reason why vercel is failing)
> 
> 
> Thanks!

Since Vercel deployed it without any red stuff does that mean that this can be merged?

**Review by capJavert — APPROVED** [review]
LGTM!

**Comment by capJavert** [comment]
@KazookiTV thanks for your contributions 🤘 cheers!

**Pull request merged**
