### PR TITLE
Some small changes.

### PR DESCRIPTION
**Pull request by Superdeathghost**
I just added a few lines. 
Nothing much. : )

Might want to check for grammar, spelling, and syntax errors though.
I already spotted a syntax error, and I can't make changes at this stage.

### CODE REVIEW

**Review by capJavert — CHANGES_REQUESTED** [review]
@Superdeathghost yeah.. just a few lines.. 🤘 

I would love to merge this but you will need to do the following:
- reformat your JSON changes to tabs (4 spaces) - because like this it looks like you changed the whole file and I can not clearly review your changes
- JSON is still not valid, you can use https://jsonlint.com/ to validate your JSON syntax

Thanks!

**Review by capJavert — CHANGES_REQUESTED** [review]
> reformat your JSON changes to tabs (4 spaces) - because like this it looks like you changed the whole file and I can not clearly review your changes

You only formatted first level indentations to 4 spaces, the whole file needs to be formatted like this.

**Review by capJavert — APPROVED** [review]

**Comment by capJavert** [comment]
Tnx @Superdeathghost for this "small" addition ;)

**Comment by Superdeathghost** [comment]
Glad to have contributed to the greater good. :D

**Pull request merged**
